services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hydraulic
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  api:
    build: ../apps/api
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/hydraulic?schema=public}
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["3000:3000"]
    command: >
      sh -c "npm exec prisma db push -- --schema=/app/prisma/schema.prisma &&
             node dist/main.js"

  web:
    build: ../apps/web
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    depends_on: [ api ]
    ports: ["3001:3001"]
    command: ["npm","start","-p","3001"]

volumes: { pgdata: {} }
